alter table public.company_customization
add column if not exists custom_order_slip_enabled boolean not null default true,
add column if not exists custom_order_slip_auto_print boolean not null default false,
add column if not exists custom_order_slip_title text not null default 'Customer''s Order Slip',
add column if not exists custom_order_slip_contact_line text not null default '',
add column if not exists custom_order_slip_email_line text not null default '',
add column if not exists custom_order_slip_footer_note text not null default 'Please keep this slip for your records.',
add column if not exists custom_order_slip_blank_detail_lines integer not null default 4,
add column if not exists custom_order_slip_show_logo boolean not null default true,
add column if not exists custom_order_slip_show_order_number boolean not null default true,
add column if not exists custom_order_slip_show_due_date boolean not null default true,
add column if not exists custom_order_slip_show_customer_phone boolean not null default true,
add column if not exists custom_order_slip_show_customer_account boolean not null default true,
add column if not exists custom_order_slip_show_store boolean not null default true,
add column if not exists custom_order_slip_show_device boolean not null default true,
add column if not exists custom_order_slip_show_cashier boolean not null default true,
add column if not exists custom_order_slip_show_line_items boolean not null default true,
add column if not exists custom_order_slip_show_pricing boolean not null default true,
add column if not exists custom_order_slip_show_payment_summary boolean not null default true,
add column if not exists custom_order_slip_show_payment_reference boolean not null default true,
add column if not exists custom_order_slip_show_taken_by boolean not null default true,
add column if not exists custom_order_slip_show_signatures boolean not null default true;
